### ISSUE TITLE
Finding error while doing pip install PiML

### ISSUE THREAD

**Issue by Chandrima31** [SelfExplainML/PiML-Toolbox#15]
Hello, I am getting the following error while running installation of PiML. Please help me resolve. Thanks.
![image](https://user-images.githubusercontent.com/44930259/193466834-1f4424f6-003f-4eac-8354-ac89261cb27a.png)

**Comment by ZebinYang** [comment]
Hi @Chandrima31 , it seems that these conflicts were due to your existing packages. PiML does not have such strict constraints.
