### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by Love-R** [SelfExplainML/PiML-Toolbox#18]
Hi, this project looks really interesting and I would love to try it out. However, I can't install it on 64-bit Ubuntu 20.04 under various Python versions (3.8, 3.9, and 3.10). The error message is just:

> ERROR: Could not find a version that satisfies the requirement PiML
ERROR: No matching distribution found for PiML

Is this expected? Are there only some operating systems supported?

**Comment by ZebinYang** [comment]
Hi @Love-R,

PiML currently supports various os platforms and python versions, including [py37, py38, py39] * [Win, Linux, and Macos]. 

It is supposed to work on 64-bit Ubuntu 20.04 + py38 ~ py39. 

Could you try "pip install https://files.pythonhosted.org/packages/44/97/03c0da48efb1b80b23b74b4d34c714bb7aafc7cf9e817d2db6d22a105e52/PiML-0.3.3.post0-cp38-none-manylinux_2_17_x86_64.whl" on py3.8 again?

**Comment by Love-R** [comment]
Hi @ZebinYang ,

 ```
pip install https://files.pythonhosted.org/packages/44/97/03c0da48efb1b80b23b74b4d34c714bb7aafc7cf9e817d2db6d22a105e52/PiML-
0.3.3.post0-cp38-none-manylinux_2_17_x86_64.whl
```
Initially yielded
```
ERROR: PiML-0.3.3.post0-cp38-none-manylinux_2_17_x86_64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 19.2.3, however version 22.3 is available.
```
on Python3.8. When I upgraded my pip version to 22.3, the installation worked - thank you!

**Comment by ZebinYang** [comment]
@Love-R, 

I see. 
Thanks for your interest in PiML.
