### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MLrsearch** [SelfExplainML/PiML-Toolbox#19]
Dear,
Is there somewhere extended documentation about the toolbox, its functionalities and different input possibilities? Now, I tried to deduce it from the examples. Furthermore, the interpretability results for the 10 most important features are given. But how could I get it for all features?

Many thanks.

**Comment by ZebinYang** [comment]
Hi @MLrsearch, 

Thanks for your suggestions.
We are now working on the documentation of PIML and it will be released in a few months.
As for the limitation of feature importance plots, we will improve them in future releases.
