### ISSUE TITLE
Add histogram in LLM-summary

### ISSUE THREAD

**Issue by analyticsneu** [SelfExplainML/PiML-Toolbox#2]
Would be nice to have a histogram for exp.model_interpret() -> LLM-summary

**Comment by ajzhanghk** [comment]
Thanks for a good suggestion. We will have it in a future release.

**Comment by ajzhanghk** [comment]
@analyticsneu In the upcoming V0.1.4, we've added a violin plot of LLM coefficients in model_interpret for ReLU-DNN. Please check it out.
