### ISSUE TITLE
What does the back end run on?

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#20]
I know that this project is not currently open source, but would it be possible to know what packages the backend uses? Do you use scikit-learn to calculate most of the interpretability measurements? This would be useful to know because it tells us exactly how these metrics are calculated. For example, permutation feature importance can be calculated in multiple different ways. One can permute the observations of each feature n times, or one can swap the observations of one feature with those of another. Also, there are several different metrics one can use to quantify permutation feature importance (R2, MSE, or RMSE for regression models and accuracy, precision, etc. for classification models).

Thank you

**Comment by ZebinYang** [comment]
Hi, @xloffree 

You are right. 

All the post-hoc explanations metrics are based on external tools or packages.
- The permutation feature importance is calculated using scikit-learn's API, and we use its default metrics for regression and classification tasks, respectively.
- PDP is also based on scikit-learn, and ALE is based PyALE package.
- The calculation of LIME and SHAP is based on the packages 'lime' and 'shap', respectively.

While most of the intrinsic interpretability and model diagnostics are calculated by our own internal functions.
