### ISSUE TITLE
Output coefficients for glm

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#22]
Hi,

Is there a way to output all of the estimated coefficients for a trained GLM model? I see there is a plot displaying the coefficients but is there a way to output them in a list or something that can be saved?

Thank you

**Comment by ZebinYang** [comment]
Hi @xloffree,

The coefficients of a GLM model can be extracted using
```
exp.get_model("GLM").estimator.coef_
```
