### ISSUE TITLE
Error with training classification models

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#23]
Hi, 
When training classification models, I get the following error:

UnboundLocalError                         Traceback (most recent call last)
File piml/dashboard/model_panel.py:419, in piml.dashboard.model_panel.ModelTrainingPanel.train_register_panel.train_data_f()

UnboundLocalError: local variable 'df' referenced before assignment

Do you know how to fix this?

Thank you

**Comment by ZebinYang** [comment]
Can you provide a reproducible notebook or code snapshot?

**Comment by xloffree** [comment]
Seems to be working now. I will reach out if I run into it again. Thanks
