### ISSUE TITLE
Interpretation of L1 and L2 values in GLM options

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#24]
Hi,

What exactly do the L1 and L2 values refer to in the GLM model? Is it the lambda value or the lambda value multiplied by the alpha (or 1-alpha)? I got a result where the elastic net model selected zero variables, which was a very unexpected result. Consequently, I am suspecting that I am misinterpreting what the L1 and L2 values are referring to in PiML.

Thank you

**Comment by CnBDM-Su** [comment]
Hi @xloffree ,
With different L1 and L2, the GLM model will changed.

- {l1_regularzation=0 & l2_regularzation=0}: Ordinary least squares Linear Regression.
- {l1_regularzation>0 & l2_regularzation=0}: Lasso Regression.
- {l1_regularzation=0 & l2_regularzation>0}: Ridge Regression.
- {l1_regularzation>0 & l2_regularzation>0}: Elasticnet Regression.

For Lasso, alpha= l1,
For Ridge, alpha=l2,
For Elasticnet, alpha=l1+l2; l1_ratio= l1/ alpha

**Comment by xloffree** [comment]
Hi, 

Thank you for the response.

When using PiML, if I have a lambda value of 0.1 and an alpha value of 0.5, what value should I enter in for L1 and L2 when using elastic net? Would it be 0.05?

Thank you

![image](https://user-images.githubusercontent.com/64742457/213279684-b489c458-6bb6-4bf5-b56b-bbf2db332782.png)
