### ISSUE TITLE
GLM with cross validation

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#27]
Hi,

I want to run GLM with cross validation and then view the interpretability results with PiML. I tried to do the following but got an error.
How can I do this?

Thank you

![image](https://user-images.githubusercontent.com/64742457/216443508-a907dddc-6084-437a-beaa-c48ef113c299.png)

**Comment by CnBDM-Su** [comment]
@xloffree 
It seems I cannot reproduce your error. Can you try to input numpy.array instead of pandas.Dataframe?
![image](https://user-images.githubusercontent.com/26788062/217418117-166b67e0-6e05-44b6-9fd6-c28a6bfe07f3.png)
