### ISSUE TITLE
Elastic net removes all predictors

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#28]
Hi,

When I try to run elastic net in PiML, I can get an r2 value and other global interpretability metrics, but when I try to look at the influence of individual predictors, I see that the model has removed each predictor. When running code in sklearn that should give identical results, elastic net does not remove all of the predictors. I am not sure what is going on here. Perhaps it is some kind of bug?

Thank you

**Comment by CnBDM-Su** [comment]
> Hi,
> 
> When I try to run elastic net in PiML, I can get an r2 value and other global interpretability metrics, but when I try to look at the influence of individual predictors, I see that the model has removed each predictor. When running code in sklearn that should give identical results, elastic net does not remove all of the predictors. I am not sure what is going on here. Perhaps it is some kind of bug?
> 
> Thank you

Hi @xloffree , Can you offer the code you used? Then I can do the test for answering your question. Thanks

**Comment by xloffree** [comment]
![Screenshot (313)](https://user-images.githubusercontent.com/64742457/220999163-3ae5c029-a241-4e89-99e4-3e723371de37.png)
![Screenshot (312)](https://user-images.githubusercontent.com/64742457/220999169-8addcb30-4baf-48b8-b8c8-d0ede7567bcf.png)
![Screenshot (311)](https://user-images.githubusercontent.com/64742457/220999177-22187b52-9e34-432d-a288-35db18554b0d.png)
![Screenshot (310)](https://user-images.githubusercontent.com/64742457/220999182-c9e07765-9a25-4fc8-8a06-9c792f2de514.png)
![Screenshot (309)](https://user-images.githubusercontent.com/64742457/220999184-cef3b7b4-730d-4158-ba29-e59e9892a704.png)

As you can see, I am running elastic net in PiML and sklearn. I should be getting the same results, or at the very least, PiML elastic net should not be removing every predictor.

**Comment by ZebinYang** [comment]
Hi @xloffree, 

Note that the data used by PiML is preprocessed to be within 0 and 1. 
If you want to get the same results as sklearn's ElasticNest, please fit the model using the data preprocessed by PiML.

```
train_x, train_y, sample_weight_train = exp.get_data(train=True)
```
