### ISSUE TITLE
Add rule-based interpretable models?

### ISSUE THREAD

**Issue by csinva** [SelfExplainML/PiML-Toolbox#3]
Hi, I really like this package you've built, especially the data preparation / eda.

I've been developing the [imodels package](https://github.com/csinva/imodels), which provides access to a bunch of inherently interpretable models. It would be really cool to be able to use some of these models (e.g. RuleFit, FIGS) in this toolbox too!

Best,
Chandan

**Comment by ajzhanghk** [comment]
Hi Chandan, it's great to have your comment. The imodels package is brilliant and it has a very good coverage of rule-based interpretable models! We definitely would like to give it a try to include RuleFit into the PiML toolbox.  -- Aijun

**Comment by asudjianto** [comment]
@ajzhanghk we should put FIGS in PiML.

**Comment by ZebinYang** [comment]
Hi @csinva 

The PiML team has just released version 0.4.0, which includes FIGS as a built-in interpretable model.

You may want to try it using one of our example notebooks, e.g., https://colab.research.google.com/github/SelfExplainML/PiML-Toolbox/blob/main/examples/Example_BikeSharing.ipynb. 
Follow the predefined steps for data loading, summary, preparation, and then choose FIGS in the exp.model_train panel. 

Thanks,
Zebin

**Comment by ajzhanghk** [comment]
@csinva Thanks for your great work on FIGS, a very neat version of interpretable rules. We have re-engineered FIGS with much faster speed and integrated it into PiML V0.4.0. Please try it out and let us know your thoughts.

**Comment by csinva** [comment]
Thanks for including it! I've been playing with it and it's working really well :smile: I'll be recommending PiML to all the interpretability folks I know!

P.S. If you found FIGS useful, I think you might also want to add [HSTree](https://csinva.io/imodels/shrinkage.html). It's easier to implement, faster, and when we were benchmarking [interpretable methods in autogluon](https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-interpretability.html), it consistently performed at the top.
