### ISSUE TITLE
Example codes do not run on Colab

### ISSUE THREAD

**Issue by jtonh** [SelfExplainML/PiML-Toolbox#33]
Hi,

I am running the PiML examples on Colab via the links in this Github Repo. Those example notebooks worked on Colab about 1 month ago, but they do not work now. Here are the errors:

!pip install piml
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.

!pip install numpy==1.23.5
!pip install xgboost==1.7.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pygam 0.9.0 requires numpy<2.0.0,>=1.24.2, but you have numpy 1.23.5 which is incompatible.

from piml import Experiment
exp = Experiment()
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

Would you please sort out how to fix the errors?

Thanks

**Comment by ZebinYang** [comment]
Hi @jtonh,

After you installed the required packages, you may need to restart the kernel

![image](https://user-images.githubusercontent.com/47017147/230257279-d215254a-6334-43e3-8896-164b66956af4.png)

Then, run import piml directly.
```
from piml import Experiment
exp = Experiment()
```

**Comment by jtonh** [comment]
Hi Zebin,

It works now.

Thank you very much,
