### ISSUE TITLE
Where are the source codes

### ISSUE THREAD

**Issue by jtonh** [SelfExplainML/PiML-Toolbox#35]
Hi,

In order to learn the details of the different algorithms and how to implement them, I am wondering whether the source codes of the different algorithms such as GAMI-Net, Unwrapping Deep ReLu, fairess, etc are available? What programing language do you use to write the algorithms?

Thanks,

**Comment by ZebinYang** [comment]
Hi @jtonh,

PiML is developed based on Python. However, the source codes are not open-sourced for the time being.
For the GAMI-Net model, refer to the source codes (https://github.com/ZebinYang/gaminet) I developed years ago.
