### ISSUE TITLE
exp.data_prepare() not working

### ISSUE THREAD

**Issue by xloffree** [SelfExplainML/PiML-Toolbox#36]
Hi,

I am simply trying to run piml with an imported dataset. This is what I have:

`from piml import Experiment
exp=Experiment()
exp.data_loader(data=data)
exp.data_summary()
exp.data_prepare()`

Then I get the following error:

`---> 1 exp.data_prepare()

File piml/api.py:179, in piml.api.Experiment.data_prepare()

File piml/api.py:816, in piml.api.Experiment._data_prepare_panel()

File piml/workflow/data_api.py:112, in piml.workflow.data_api.DataAPI.prepare_model()

File piml/workflow/base.py:54, in piml.workflow.base.Model.__init__()

File piml/workflow/base.py:175, in piml.workflow.base.Model.model_prepare()

File piml/models/glm.py:17, in piml.models.glm.GLMRegressor.__init__()

File piml/models/glm.py:225, in piml.models.glm.PiLinearRegression.__init__()

TypeError: __init__() got an unexpected keyword argument 'normalize'`

How can I resolve this?

Thank you

**Comment by ZebinYang** [comment]
Hi @xloffree, 

This is an error due to API changes in the dependency package scikit-learn>=1.2.0.

It can be solved by upgrading piml to the latest version by "pip install piml -U".
