### ISSUE TITLE
Link to OpenTeams Videos somewhere here

### ISSUE THREAD

**Issue by jphall663** [SelfExplainML/PiML-Toolbox#37]
Would it be nice to link to the OpenTeams PiML videos/playlist (e.g., https://www.youtube.com/watch?v=R79JGIMf6PY) somewhere here?

Also, please just close if they are already linked! But I didn't see them ...

**Comment by jphall663** [comment]
Perhaps better on the github pages portal?

**Comment by analyticsneu** [comment]
We have one here @jphall663 
https://academy.qusandbox.com/market/62bc6553347b3c0d73adcc7b

**Comment by ZebinYang** [comment]
Hi @jphall663 and @analyticsneu, thanks for your advice. The OpenTeams video link is now added to this page https://github.com/SelfExplainML/PiML-Toolbox/tree/main/docs/Workshop
