### ISSUE TITLE
Installation on Macbook Pro M1 architecture

### ISSUE THREAD

**Issue by parunach** [SelfExplainML/PiML-Toolbox#4]
This is not installable on M1 architecture machines. Can this be installed from the git repo?

**Comment by ajzhanghk** [comment]
Seems like we really have to get a latest MacBook with M1 Pro or Max chip. We'll try to make PiML installable on M1😄

**Comment by Eveyz** [comment]
> This is not installable on M1 architecture machines. Can this be installed from the git repo?

Hi @parunach, can you post the error message here? Probably with your python version.

**Comment by parunach** [comment]
Python version: 3.9.7

Error with pip:
_ERROR: Could not find a version that satisfies the requirement PiML (from versions: none)
ERROR: No matching distribution found for PiML_

When I tried to get

**Comment by ajzhanghk** [comment]
> Python version: 3.9.7
> 
> Error with pip: _ERROR: Could not find a version that satisfies the requirement PiML (from versions: none) ERROR: No matching distribution found for PiML_

So far we have only compiled versions for MacOS 10.14_x86_64 (for Python 3.7, 3.8, 3.9).  "pip install piml" runs okay on an M1 architecture machine. Can you share which versions you have for MacOS and Python? Thanks.

**Comment by asudjianto** [comment]
I installed it successfully in M1 (not Max). I have to install an older version of LightGBM because the latest version doesn’t run on M1.

**Comment by parunach** [comment]
When I run the pip in my machine, I get

ERROR: Could not find a version that satisfies the requirement piml (from versions: none)
ERROR: No matching distribution found for piml

**Comment by virtualitics-joseph** [comment]
Hi, I'm also having an issue installing on Macbook Pro M1 Architecture.

Running this on mac M1 pro, Monterey v12.6 on Python v3.9.12

The error message I'm receiving is different. 

<img width="1436" alt="Screen Shot 2022-11-08 at 10 48 51 AM" src="https://user-images.githubusercontent.com/93666911/200853942-43a76b1c-8768-4334-93eb-f1254022791c.png">

**Comment by ZebinYang** [comment]
Hi @virtualitics-joseph, this is an error due to lightgbm on MacOS. 
You may reinstall lightgbm using the solution in the following link.
https://stackoverflow.com/questions/50889162/lightgbm-image-not-found-after-mac-install

**Comment by ZebinYang** [comment]
Hi @parunach, 

I also encountered this error with an old version of pip.
You may need to upgrade your pip to the latest version via "pip install pip -U", and then run "pip install piml".

**Comment by ZebinYang** [comment]
Closed as starting from PiML-0.5.1, Mac M1 is supported with Python 3.8, 3.9, and 3.10.
