### ISSUE TITLE
Support Spearman correlation?

### ISSUE THREAD

**Issue by jphall663** [SelfExplainML/PiML-Toolbox#41]
Spearman correlation may better inform monotonicity constraints vs. Pearson correlation. 

Would just be nice to see in addition to Pearson correlation in `feature_select()`.

**Comment by ZebinYang** [comment]
Hi @jphall663, 

Starting from v0.5.0, the Spearman correlation-based feature selection has been added, see the user guides.
https://selfexplainml.github.io/PiML-Toolbox/_build/html/guides/data/feature_select.html#correlations

**Comment by jphall663** [comment]
Yep I see it - thanks!

I have some other notes I'll post here in coming days.
