### ISSUE TITLE
Export visualization

### ISSUE THREAD

**Issue by ShanshanBiNovelis** [SelfExplainML/PiML-Toolbox#6]
Hi, thanks for making this tool. I just wonder is there anyway to export the plots. Sometimes, our engineers don't have jupter, and we need to make a UI for them. I wonder if we can use PiML in the backend, save the plot in the backend and show the plots in the frond end. Thanks.

**Comment by ajzhanghk** [comment]
Hi, thanks for the suggestion. We'll consider this or make it partially available (e.g. save the plots) in a future release.
